name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
          
      - name: Validate, build and run tests
        run: mvn --batch-mode --update-snapshots verify
        
      - name: Have GitHub Actions package maven project
        run: mvn -B package --file pom.xml
        
      - name: check the target folder
        run: |
          cd target
          ls -a
